spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: stormers
            client-secret: stormers.7
            authorization-grant-type: client_credentials
            scope:
            - bid
        provider:
          sso:
            issuer-uri: https://login.sso.az.run.withtanzu.com
